import { Geist, Geist_Mono } from 'next/font/google';
import '@/styles/reset.css.js';
import '@/styles/globals.css.js';
import GlobalLayout from '@/components/layouts/GlobalLayout';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata = {
  title: 'App router with market',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <GlobalLayout>{children}</GlobalLayout>
    </html>
  );
}
